export { default as Email } from './email'
export { default as Layout } from './layout'
export { default as Menu } from './menu'
export { default as NavBar } from './navbar'
export { default as Seo } from './seo'
export { default as Side } from './side'
export { default as Social } from './social'
