export { default as Icon } from './icon'
export { default as IconGitHub } from './github'
export { default as IconInstagram } from './instagram'
export { default as IconLogo } from './logo'
export { default as IconLogoHover } from './logoHover'
