name: Production Build

on:
  push:
    branches: [main]

env:
  GATSBY_EMJINX_API_KEY: ${{ secrets.GATSBY_EMJINX_API_KEY }}
  GATSBY_EMJINX_API_URL: ${{ vars.GATSBY_EMJINX_API_URL }}
  GATSBY_GTAG_ID: ${{ secrets.GATSBY_GTAG_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Gatsby Install
        run: npm install -g gatsby-cli
      - name: Dependency Install
        run: npm install
      - name: Gatsby Build
        run: gatsby build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION_NAME }}
          SOURCE_DIR: 'public'

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.AWS_REGION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
